version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: pokedex-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: super@admin
      MYSQL_DATABASE: pokedexdb
      MYSQL_USER: dev
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  pokedex-api:
    build: .
    container_name: pokedex-api
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/pokedexdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - mysql-db
    restart: unless-stopped

volumes:
  mysql-data:
